/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-06-25 03:47:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._13.freeboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboardReplyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자유게시글 댓글등록</title>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 섬머노트를 div를 활용한 textarea에 추가.\r\n");
      out.write("\t// http://summernote.org 활용\r\n");
      out.write("    $('#bo_content').summernote({\r\n");
      out.write("\t\t\theight: 150,\r\n");
      out.write("\t\t\tcodemirror: {\r\n");
      out.write("\t\t\ttheme: 'monokai'\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t <div class=\"col-sm-3\">\r\n");
      out.write("\t\t <label class=\"col-sm-2 control-label\">No :</label>\r\n");
      out.write("  \t\t <p class=\"form-control-static\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <div class=\"col-sm-8\">\r\n");
      out.write("\t \t<label class=\"col-sm-2 control-label\">제목 :</label>\r\n");
      out.write("    \t<p class=\"form-control-static\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.bo_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t <div class=\"col-sm-1\">\r\n");
      out.write("\t \t<p class=\"text-right text-danger bg-danger\">의 댓글</p>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr />\r\n");
      out.write("<form class=\"form-horizontal\" role=\"form\" action=\"\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_title\">제목:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_title\" name=\"bo_title\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_nickname\">작성자 대화명:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_nickname\" name=\"bo_nickname\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_pwd\">패스워드:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" id=\"bo_pwd\" name=\"bo_pwd\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_mail\">메일:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"bo_mail\" name=\"bo_mail\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label class=\"control-label col-sm-2\" for=\"bo_content\">내용:</label>\r\n");
      out.write("\t\t<div class=\"col-sm-10\"> \r\n");
      out.write("\t\t\t<div id=\"bo_content\"><p></p></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\"> \r\n");
      out.write("\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-success\" style=\"float: right;\">답글등록</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-danger\">취소</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\">목록</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
