/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-06-11 07:08:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type='text/javascript' src='http://code.jquery.com/jquery-latest.js'></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function(){\r\n");
      out.write("      $('#btn3').on('click', function() {\r\n");
      out.write("         location.replace('");
      out.print(request.getContextPath());
      out.write("/09/main.jsp');\r\n");
      out.write("      });    \r\n");
      out.write("      $('form').submit(function() {\r\n");
      out.write("  \t\tvar mem_pass = $('input[name=mem_pass]').val();\r\n");
      out.write("  \t\tif (!mem_pass.validationPWD()) {\r\n");
      out.write("  \t\t\talert('비밀번호를 바르게 입력해주세요');\r\n");
      out.write("  \t\t\treturn false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\tvar mem_hometel = $('input[name=mem_hometel]').val();\r\n");
      out.write("  \t\tif (!mem_hometel.validationHOMETEL()) {\r\n");
      out.write("  \t\t\talert('집전화번호를 바르게 입력해주세요');\r\n");
      out.write("  \t\t\treturn false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\tvar mem_comtel = $('input[name=mem_comtel]').val();\r\n");
      out.write("  \t\tif (!mem_comtel.validationCOMTEL()) {\r\n");
      out.write("  \t\t\talert('회사전화번호를 바르게 입력해주세요');\r\n");
      out.write("  \t\t\treturn false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\tvar mem_hp = $('input[name=mem_hp]').val();\r\n");
      out.write("  \t\tif (!mem_hp.validationHP()) {\r\n");
      out.write("  \t\t\talert('휴대전화번호를 바르게 입력해주세요');\r\n");
      out.write("  \t\t\treturn false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\tvar mem_mail = $('input[name=mem_mail]').val();\r\n");
      out.write("  \t\tif (!mem_mail.validationMAIL()) {\r\n");
      out.write("  \t\t\talert('이메일을 바르게 입력해주세요');\r\n");
      out.write("  \t\t\treturn false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\treturn true;\r\n");
      out.write("  \t});\r\n");
      out.write("      \r\n");
      out.write("   })\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".fieldName {text-align: center; background-color: #f4f4f4;}\r\n");
      out.write(".tLine {background-color: #d2d2d2; height: 1px;}\r\n");
      out.write(".btnGroup { text-align: right; }\r\n");
      out.write("td {text-align: left; }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"memberForm\" action='");
      out.print(request.getContextPath() );
      out.write("/09/insertMemberInfo.jsp' method=\"post\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   <tr><td rowspan=\"13\" class=\"pic\" colspan=\"2\" style=\"vertical-align: bottom; width: 150px; text-align: center;\">\r\n");
      out.write("         <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/image/btn_pic.gif\" alt=\"사진올리기\" class=\"btn\" title=\"인적사항에 올릴 증명   을 검색합니다.\" \r\n");
      out.write("            style=\"cursor: pointer;\"/><br/>\r\n");
      out.write("         <div style=\"width: 100%\" align=\"center\">\r\n");
      out.write("            size : 235x315 이하\r\n");
      out.write("         </div>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">성 명</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_name\" value=\"\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">주민등록번호</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_regno1\" size=\"6\" value=\"\"/>\r\n");
      out.write("           <input type=\"text\" name=\"mem_regno2\" size=\"7\" value=\"\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">생년월일</td>\r\n");
      out.write("      <td>\r\n");
      out.write("            <input type=\"hidden\" name=\"mem_bir\" />\r\n");
      out.write("            <input type=\"text\" name=\"mem_bir1\" size=\"4\" value=\"\" />년\r\n");
      out.write("            <input type=\"text\" name=\"mem_bir2\" size=\"2\" value=\"\" />월\r\n");
      out.write("            <input type=\"text\" name=\"mem_bir3\" size=\"2\" value=\"\" />일\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">아이디</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_id\" value=\"\">&nbsp;&nbsp;<b><a href=\"#\">[ID 중복검사]</a></b>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">비밀번호</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_pass\" value=\"\" /> 8 ~ 20 자리 영문자 및 숫자 사용\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">비밀번호확인</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_pass_confirm\" value=\"\" /> 8 ~ 20 자리 영문자 및 숫자 사용\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top: 10px;\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">전화번호</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <div>\r\n");
      out.write("         <input type=\"hidden\" name=\"mem_hometel\"/>\r\n");
      out.write("         <select name=\"mem_hometel1\">\r\n");
      out.write("            <option value=\"02\">02</option>\r\n");
      out.write("            <option value=\"031\">031</option>\r\n");
      out.write("            <option value=\"032\">032</option>                                   \r\n");
      out.write("            <option value=\"033\">033</option>                       \r\n");
      out.write("            <option value=\"041\">041</option>\r\n");
      out.write("            <option value=\"042\">042</option>                       \r\n");
      out.write("            <option value=\"043\">043</option>                       \r\n");
      out.write("            <option value=\"051\">051</option>                       \r\n");
      out.write("            <option value=\"052\">052</option>\r\n");
      out.write("            <option value=\"053\">053</option>                                              \r\n");
      out.write("            <option value=\"061\">061</option>\r\n");
      out.write("            <option value=\"062\">062</option>\r\n");
      out.write("            <option value=\"063\">063</option>                                                                     \r\n");
      out.write("            <option value=\"064\">064</option>                                                                     \r\n");
      out.write("            <option value=\"070\">070</option>                                                                     \r\n");
      out.write("         </select>   -    \r\n");
      out.write("         <input type=\"text\" name=\"mem_hometel2\" size=\"4\" value=\"\" /> - \r\n");
      out.write("         <input type=\"text\" name=\"mem_hometel3\" size=\"4\" value=\"\" />\r\n");
      out.write("         </div>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">핸드폰</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"hidden\" name=\"mem_hp\"/>\r\n");
      out.write("         <select name=\"mem_hp1\">\r\n");
      out.write("            <option value=\"010\">010</option>\r\n");
      out.write("            <option value=\"016\">016</option>                       \r\n");
      out.write("            <option value=\"017\">017</option>                       \r\n");
      out.write("            <option value=\"019\">019</option>                       \r\n");
      out.write("         </select>   -\r\n");
      out.write("         <input type=\"text\" name=\"mem_hp2\" size=\"4\" value=\"\" /> - \r\n");
      out.write("         <input type=\"text\" name=\"mem_hp3\" size=\"4\" value=\"\" />\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">이메일</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"hidden\" name=\"mem_mail\" />\r\n");
      out.write("         <input type=\"text\" name=\"mem_mail1\" value=\"\" /> @\r\n");
      out.write("         <select name=\"mem_mail2\">\r\n");
      out.write("            <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("            <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("            <option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("            <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("            <option value=\"gmail.com\">gmail.com</option>            \r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("      \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">주소</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"hidden\" name=\"mem_zip\" />\r\n");
      out.write("         <input type=\"text\" name=\"mem_zip1\" id=\"mem_zip1\" size=\"3\" value=\"\" /> - \r\n");
      out.write("         <input type=\"text\" name=\"mem_zip2\" id=\"mem_zip2\" size=\"3\" value=\"\" />\r\n");
      out.write("         <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--accent\" type=\"button\">우편번호검색</button><br>\r\n");
      out.write("         <input type=\"text\" name=\"mem_add1\" id=\"mem_add1\" value=\"\" />\r\n");
      out.write("         <input type=\"text\" name=\"mem_add2\" id=\"mem_add2\" value=\"\" />\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">직 업</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_job\" value=\"\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"fieldName\" width=\"100px\" height=\"25\">취 미</td>\r\n");
      out.write("      <td>\r\n");
      out.write("         <input type=\"text\" name=\"mem_like\" value=\"\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr><td class=\"tLine\" colspan=\"2\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr><td colspan=\"2\" height=\"20\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td class=\"btnGroup\" colspan=\"2\" >\r\n");
      out.write("         <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\" id=\"btn1\" type=\"submit\">가입하기</button>\r\n");
      out.write("         <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\" id=\"btn2\" type=\"reset\">취소</button>\r\n");
      out.write("         <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\" id=\"btn3\" type=\"button\">목록</button>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
